"""
HTML and CSV report export.

Generates styled analysis reports using only the standard library
(no Jinja2, no external template engines).
"""

from __future__ import annotations

import csv
import html
import os
import webbrowser
from datetime import datetime
from tkinter import filedialog, messagebox
from typing import Dict, List


# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>LFT Analysis Report</title>
<style>
  :root {{
    --bg-primary: #1a1a2e;
    --bg-secondary: #16213e;
    --bg-tertiary: #0f3460;
    --fg-primary: #e0e0e0;
    --fg-secondary: #a0a0b0;
    --accent: #bd93f9;
    --success: #50fa7b;
    --error: #ff5555;
    --warning: #f1fa8c;
    --info: #8be9fd;
    --border: #2a2a4e;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    background: var(--bg-primary);
    color: var(--fg-primary);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    padding: 24px;
  }}
  header {{
    border-bottom: 2px solid var(--accent);
    padding-bottom: 16px;
    margin-bottom: 24px;
  }}
  header h1 {{
    color: var(--accent);
    font-size: 1.8em;
    margin-bottom: 4px;
  }}
  header .meta {{
    color: var(--fg-secondary);
    font-size: 0.9em;
  }}
  h2 {{
    color: var(--accent);
    font-size: 1.3em;
    margin: 24px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--border);
  }}
  h3 {{
    color: var(--info);
    font-size: 1.1em;
    margin: 16px 0 8px;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 0.9em;
  }}
  th {{
    background: var(--bg-secondary);
    color: var(--accent);
    text-align: left;
    padding: 8px 12px;
    border: 1px solid var(--border);
    position: sticky;
    top: 0;
  }}
  td {{
    padding: 6px 12px;
    border: 1px solid var(--border);
    max-width: 400px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }}
  tr:nth-child(even) {{ background: var(--bg-secondary); }}
  tr:hover {{ background: var(--bg-tertiary); }}
  .ok {{ color: var(--success); font-weight: bold; }}
  .fail {{ color: var(--error); font-weight: bold; }}
  .summary-stats {{
    display: flex;
    gap: 24px;
    margin: 16px 0;
    flex-wrap: wrap;
  }}
  .stat-box {{
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 12px 20px;
    min-width: 140px;
  }}
  .stat-box .value {{
    font-size: 1.8em;
    font-weight: bold;
    color: var(--accent);
  }}
  .stat-box .label {{
    color: var(--fg-secondary);
    font-size: 0.85em;
  }}
  .section {{ margin-bottom: 32px; }}
  footer {{
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid var(--border);
    color: var(--fg-secondary);
    font-size: 0.8em;
    text-align: center;
  }}
</style>
</head>
<body>

<header>
  <h1>Linux Forensics Toolkit — Analysis Report</h1>
  <div class="meta">Version {version} &bull; Generated {timestamp}</div>
</header>

<div class="summary-stats">
  <div class="stat-box">
    <div class="value">{total_analyzers}</div>
    <div class="label">Analyzers Run</div>
  </div>
  <div class="stat-box">
    <div class="value">{passed}</div>
    <div class="label">Passed</div>
  </div>
  <div class="stat-box">
    <div class="value">{failed}</div>
    <div class="label">Failed</div>
  </div>
  <div class="stat-box">
    <div class="value">{total_events:,}</div>
    <div class="label">Total Events</div>
  </div>
  <div class="stat-box">
    <div class="value">{total_findings:,}</div>
    <div class="label">Total Findings</div>
  </div>
</div>

<h2>Summary</h2>
<table>
  <thead>
    <tr><th>Analyzer</th><th>Status</th><th>Events</th><th>Findings</th><th>Files</th></tr>
  </thead>
  <tbody>
{summary_rows}
  </tbody>
</table>

{detail_sections}

<footer>
  Generated by Linux Forensics Toolkit v{version}
</footer>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_html_report(
    output_dir: str | None,
    results: List[Dict],
    version: str,
    parent=None,
) -> str | None:
    """Generate and save an HTML analysis report.

    Opens a file-save dialog, writes the report, and optionally opens it
    in the default browser.  Returns the saved path, or None if cancelled.
    """
    path = filedialog.asksaveasfilename(
        parent=parent,
        title="Export HTML Report",
        defaultextension=".html",
        initialfile="lft_report.html",
        initialdir=output_dir or ".",
    )
    if not path:
        return None

    html_content = _render_html(results, version, output_dir)

    with open(path, "w", encoding="utf-8") as f:
        f.write(html_content)

    # Offer to open in browser
    try:
        webbrowser.open(f"file://{os.path.abspath(path)}")
    except Exception:
        pass

    return path


def export_csv_summary(
    output_dir: str | None,
    results: List[Dict],
    parent=None,
) -> str | None:
    """Export a single CSV summarising all analyzer results.

    Returns the saved path, or None if cancelled.
    """
    path = filedialog.asksaveasfilename(
        parent=parent,
        title="Export CSV Summary",
        defaultextension=".csv",
        initialfile="lft_summary.csv",
        initialdir=output_dir or ".",
    )
    if not path:
        return None

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Analyzer", "Status", "Events", "Findings", "Files", "Error"])
        for r in results:
            if not isinstance(r, dict):
                continue
            writer.writerow([
                r.get("name", "?"),
                "OK" if r.get("success") else "FAIL",
                r.get("event_count", 0) or 0,
                r.get("finding_count", 0) or 0,
                len(r.get("output_files", [])),
                r.get("error", ""),
            ])

    return path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_html(results: List[Dict], version: str, output_dir: str | None) -> str:
    """Build the full HTML string."""
    results = [r for r in results if isinstance(r, dict)]

    passed = sum(1 for r in results if r.get("success"))
    failed = len(results) - passed
    total_events = sum(r.get("event_count", 0) or 0 for r in results)
    total_findings = sum(r.get("finding_count", 0) or 0 for r in results)

    # Summary rows
    summary_lines = []
    for r in results:
        ok = r.get("success", False)
        cls = "ok" if ok else "fail"
        status = "OK" if ok else "FAIL"
        summary_lines.append(
            f'    <tr>'
            f'<td>{html.escape(r.get("name", "?"))}</td>'
            f'<td class="{cls}">{status}</td>'
            f'<td>{r.get("event_count", 0) or 0:,}</td>'
            f'<td>{r.get("finding_count", 0) or 0:,}</td>'
            f'<td>{len(r.get("output_files", []))}</td>'
            f'</tr>'
        )

    # Per-analyzer detail sections with CSV preview
    detail_parts = []
    for r in results:
        name = html.escape(r.get("name", "?"))
        csv_files = r.get("output_files", [])
        if not csv_files:
            continue

        section = f'<div class="section">\n<h2>{name}</h2>\n'

        for csv_path in csv_files[:3]:  # max 3 files per analyzer
            if not os.path.isfile(csv_path):
                continue
            basename = html.escape(os.path.basename(csv_path))
            section += f'<h3>{basename}</h3>\n'
            section += _csv_to_html_table(csv_path, max_rows=20)

        section += "</div>\n"
        detail_parts.append(section)

    return _HTML_TEMPLATE.format(
        version=html.escape(version),
        timestamp=html.escape(datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        total_analyzers=len(results),
        passed=passed,
        failed=failed,
        total_events=total_events,
        total_findings=total_findings,
        summary_rows="\n".join(summary_lines),
        detail_sections="\n".join(detail_parts),
    )


def _csv_to_html_table(csv_path: str, max_rows: int = 20) -> str:
    """Read a CSV file and return an HTML table string."""
    try:
        size = os.path.getsize(csv_path)
        if size > 2_000_000:  # 2 MB safety limit
            return "<p><em>File too large for inline preview.</em></p>\n"

        with open(csv_path, "r", newline="", errors="replace") as f:
            reader = csv.reader(f)
            headers = next(reader, None)
            if not headers:
                return "<p><em>Empty CSV.</em></p>\n"

            # Cap columns at 10
            max_cols = 10
            truncated_cols = len(headers) > max_cols
            headers = headers[:max_cols]

            parts = ["<table>\n<thead><tr>"]
            for h in headers:
                parts.append(f"<th>{html.escape(h[:80])}</th>")
            if truncated_cols:
                parts.append("<th>...</th>")
            parts.append("</tr></thead>\n<tbody>\n")

            count = 0
            for row in reader:
                if count >= max_rows:
                    break
                parts.append("<tr>")
                for cell in row[:max_cols]:
                    val = cell[:80] if len(cell) > 80 else cell
                    parts.append(f"<td>{html.escape(val)}</td>")
                if truncated_cols:
                    parts.append("<td>...</td>")
                parts.append("</tr>\n")
                count += 1

            parts.append("</tbody></table>\n")

            if count >= max_rows:
                parts.append(
                    f"<p><em>Showing first {max_rows} rows.</em></p>\n"
                )

            return "".join(parts)

    except Exception:
        return "<p><em>Could not read CSV file.</em></p>\n"
